### ISSUE TITLE
Cannot create changeset

### ISSUE THREAD

**Issue by cyper85** [osmlab/osm-auth#45] opened 2017-03-18 20:54 UTC
If I want to create a new changeset, I get everytime a "401 - Unauthorized".

```javascript
auth.xhr({
    method: 'GET',
    path: '/api/0.6/user/details'
}, done);
```
succeeded

```javascript
auth.xhr({
            method: 'GET',
            path: '/api/0.6/permissions'
}, function(err, details) {
            console.log(err);
            console.log(details);
});
```

succeeded with following permissions:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="OpenStreetMap Server">
  <permissions>
    <permission name="allow_read_prefs"/>
    <permission name="allow_write_api"/>
    <permission name="allow_write_notes"/>
  </permissions>
</osm>
```

But if I create a new Changeset with:

```javascript
auth.xhr({
        method: 'PUT',
        path: '/api/0.6/changeset/create',
        content:
            '<osm>'+
                '<changeset>'+
                    '<tag k="created_by" v="xxxxxxxxxxxxxxxx"/>'+
                    '<tag k="comment" v="Testing"/>'+
                '</changeset>'+
            '</osm>'
    }, function(err, details) {
        console.log(err);
        console.log(details);
});
```

I get 

> Request URL:http://www.openstreetmap.org/api/0.6/changeset/create
> Request Method:PUT
> Status Code:401 Unauthorized 

I test from a localhost-environment.

**Comment by cyper85** [comment] 2017-03-22 21:21
Okay, I found the mistake: The xhr-function handle the content as “application/x-www-form-urlencoded” and not as "text/xml". If I set the Content-Type by hand, every thing works fine.

```javascript
auth.xhr({
        method: 'PUT',
        path: '/api/0.6/changeset/create',
        dataType: "text/xml",
        options: {header: {"Content-Type": "text/xml"}},
        content:
            '<?xml version="1.0" encoding="UTF-8"?>'+
            '<osm version="0.6" generator="JOSM">'+
                '<changeset>'+
                    '<tag k="created_by" v="xxxxxx"/>'+
                    '<tag k="comment" v="test osmauth"/>'+
                '</changeset>'+
            '</osm>'
        }, function(err, details) {
            console.log(err);
            console.log(details);
        });
```

**Comment by tmcw** [comment] 2017-03-22 21:30
Yep, you'll need to specify the proper header for that request. Closing, not a bug.

**Closed by tmcw** 2017-03-22 21:30 UTC
